#!/bin/bash
#===================================================================================
#
# FILE: pullpush_functions
#
# DESCRIPTION: This file will contain functions used by the Pullpush scripts.
#
# AUTHOR: Kevin Bailey, kbailey@freewayprojects.com
# COMPANY: Freeway Projects Limited
#===================================================================================

# Check the Pullpush configuration file exists.
__load_configuration_file () {

    if [ -e /etc/pullpush/pullpush.conf ]
    then
	source /etc/pullpush/pullpush.conf
	return 0
    else
	echo "ERROR - Pullpush configuration file not found."
	return 1
    fi
}

__create_mysql_database_and_user_account () {

    DATABASE_NAME=${1}
    DATABASE_USER=${2}
    DATABASE_PASSWORD=${3}

    case "${PROJECT_TYPE}" in
	
	drupal6|drupal7)
            echo
	    echo `date`
	    echo "Creating a database for a ${PROJECT_TYPE} site..."

##	    mysqladmin --force drop ${DATABASE_NAME}
	    mysqladmin create ${DATABASE_NAME}
	    mysql --execute="GRANT ALL ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" 	    ${DATABASE_NAME}
            ;;

	*)
            echo "Error - Invalid project type."
            exit -1
    esac
}


__set_up_vhost () {

    VHOST_NAME=${1}
    DOC_ROOT=${2}

    case "${SERVER_TYPE}" in

	debian|ubuntu)

	# First we need to copy the relevant vhost template file.
	    case ${PROJECT_TYPE} in
		drupal6|drupal7)
		    sudo cp /usr/local/share/pullpush/vhost_drupal.template /etc/apache2/sites-available/${VHOST_NAME}
                    ;;
		*)
		    echo "Error - Invalid project type."
		    exit -1
            esac

	    # Edit the configuration file.  There may be a better way to do this.
            sudo sed -i "s|documentroot|${DOC_ROOT}|g" /etc/apache2/sites-available/${VHOST_NAME}
            sudo sed -i "s/username/${USER}/g" /etc/apache2/sites-available/${VHOST_NAME}
            sudo sed -i "s/vhostname/${VHOST_NAME}/g" /etc/apache2/sites-available/${VHOST_NAME}
            sudo sed -i "s/serverfqdn/${SERVER_FQDN}/g" /etc/apache2/sites-available/${VHOST_NAME}
            sudo sed -i "s/serveradminemail/${SERVER_ADMIN_EMAIL}/g" /etc/apache2/sites-available/${VHOST_NAME}

            sudo a2ensite ${VHOST_NAME}
            sudo apache2ctl restart
            ;;

	*)
            echo "Error - Invalid server type."
            exit -1
    esac

}


